name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Catch common mistakes
      run: cargo clippy -- -D warnings
    - name: Build and Test
      run: cargo test --verbose
